language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
sudo: required
script: sudo bash -ex .travis-opam.sh # sudo because we're going to use tuntap
env:
  global:
  - PACKAGE=mirage-net-fd EXTRA_REMOTES="git://github.com/mirage/mirage-dev.git"
  matrix:
  - OCAML_VERSION=4.02
  - OCAML_VERSION=4.03
