language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex ./.travis-docker.sh
env:
  global:
  - PACKAGE="mirage-net-fd"
  matrix:
  - DISTRO="debian-testing" OCAML_VERSION="4.03.0"
  - DISTRO="alpine-3.5" OCAML_VERSION="4.04.0"
